export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

// Category.
export const READ_CATEGORY = "READ_CATEGORY";
export const READ_CATEGORY_PENDING = "READ_CATEGORY_PENDING";
export const READ_CATEGORY_SUCCESS = "READ_CATEGORY_SUCCESS";
export const READ_CATEGORY_FAILURE = "READ_CATEGORY_FAILURE";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_PENDING = "CREATE_CATEGORY_PENDING";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_PENDING = "UPDATE_CATEGORY_PENDING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_PENDING = "DELETE_CATEGORY_PENDING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

// end category

//film
export const READ_FILM = "READ_FILM";
export const READ_FILM_PENDING = "READ_FILM_PENDING";
export const READ_FILM_SUCCESS = "READ_FILM_SUCCESS";
export const READ_FILM_FAILURE = "READ_FILM_FAILURE";

export const CREATE_FILM = "CREATE_FILM";
export const CREATE_FILM_PENDING = "CREATE_FILM_PENDING";
export const CREATE_FILM_SUCCESS = "CREATE_FILM_SUCCESS";
export const CREATE_FILM_FAILURE = "CREATE_FILM_FAILURE";

export const UPDATE_FILM = "UPDATE_FILM";
export const UPDATE_FILM_PENDING = "UPDATE_FILM_PENDING";
export const UPDATE_FILM_SUCCESS = "UPDATE_FILM_SUCCESS";
export const UPDATE_FILM_FAILURE = "UPDATE_FILM_FAILURE";

export const DELETE_FILM = "DELETE_FILM";
export const DELETE_FILM_PENDING = "DELETE_FILM_PENDING";
export const DELETE_FILM_SUCCESS = "DELETE_FILM_SUCCESS";
export const DELETE_FILM_FAILURE = "DELETE_FILM_FAILURE";
//film

//user-film favorite
export const READ_USER_FILM_FAVOR = "READ_USER_FILM_FAVOR";
export const READ_USER_FILM_FAVOR_PENDING = "READ_USER_FILM_FAVOR_PENDING";
export const READ_USER_FILM_FAVOR_SUCCESS = "READ_USER_FILM_FAVOR_SUCCESS";
export const READ_USER_FILM_FAVOR_FAILURE = "READ_USER_FILM_FAVOR_FAILURE";

export const CREATE_USER_FILM_FAVOR = "CREATE_USER_FILM_FAVOR";
export const CREATE_USER_FILM_FAVOR_PENDING = "CREATE_USER_FILM_FAVOR_PENDING";
export const CREATE_USER_FILM_FAVOR_SUCCESS = "CREATE_USER_FILM_FAVOR_SUCCESS";
export const CREATE_USER_FILM_FAVOR_FAILURE = "CREATE_USER_FILM_FAVOR_FAILURE";

export const UPDATE_USER_FILM_FAVOR = "UPDATE_USER_FILM_FAVOR";
export const UPDATE_USER_FILM_FAVOR_PENDING = "UPDATE_USER_FILM_FAVOR_PENDING";
export const UPDATE_USER_FILM_FAVOR_SUCCESS = "UPDATE_USER_FILM_FAVOR_SUCCESS";
export const UPDATE_USER_FILM_FAVOR_FAILURE = "UPDATE_USER_FILM_FAVOR_FAILURE";

export const DELETE_USER_FILM_FAVOR = "DELETE_USER_FILM_FAVOR";
export const DELETE_USER_FILM_FAVOR_PENDING = "DELETE_USER_FILM_FAVOR_PENDING";
export const DELETE_USER_FILM_FAVOR_SUCCESS = "DELETE_USER_FILM_FAVOR_SUCCESS";
export const DELETE_USER_FILM_FAVOR_FAILURE = "DELETE_USER_FILM_FAVOR_FAILURE";
//-- user film favor

//branch
export const READ_BRANCH = "READ_BRANCH";
export const READ_BRANCH_PENDING = "READ_BRANCH_PENDING";
export const READ_BRANCH_SUCCESS = "READ_BRANCH_SUCCESS";
export const READ_BRANCH_FAILURE = "READ_BRANCH_FAILURE";

export const CREATE_BRANCH = "CREATE_BRANCH";
export const CREATE_BRANCH_PENDING = "CREATE_BRANCH_PENDING";
export const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS";
export const CREATE_BRANCH_FAILURE = "CREATE_BRANCH_FAILURE";

export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const UPDATE_BRANCH_PENDING = "UPDATE_BRANCH_PENDING";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAILURE = "UPDATE_BRANCH_FAILURE";

export const DELETE_BRANCH = "DELETE_BRANCH";
export const DELETE_BRANCH_PENDING = "DELETE_BRANCH_PENDING";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_FAILURE = "DELETE_BRANCH_FAILURE";
//--branch

//schedule
export const READ_SCHEDULE = "READ_SCHEDULE";
export const READ_SCHEDULE_PENDING = "READ_SCHEDULE_PENDING";
export const READ_SCHEDULE_SUCCESS = "READ_SCHEDULE_SUCCESS";
export const READ_SCHEDULE_FAILURE = "READ_SCHEDULE_FAILURE";

export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const CREATE_SCHEDULE_PENDING = "CREATE_SCHEDULE_PENDING";
export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS";
export const CREATE_SCHEDULE_FAILURE = "CREATE_SCHEDULE_FAILURE";

export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
export const UPDATE_SCHEDULE_PENDING = "UPDATE_SCHEDULE_PENDING";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAILURE = "UPDATE_SCHEDULE_FAILURE";

export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const DELETE_SCHEDULE_PENDING = "DELETE_SCHEDULE_PENDING";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAILURE = "DELETE_SCHEDULE_FAILURE";
//--schedule

//PROMOTION
export const READ_PROMOTION = "READ_PROMOTION";
export const READ_PROMOTION_PENDING = "READ_PROMOTION_PENDING";
export const READ_PROMOTION_SUCCESS = "READ_PROMOTION_SUCCESS";
export const READ_PROMOTION_FAILURE = "READ_PROMOTION_FAILURE";

export const CREATE_PROMOTION = "CREATE_PROMOTION";
export const CREATE_PROMOTION_PENDING = "CREATE_PROMOTION_PENDING";
export const CREATE_PROMOTION_SUCCESS = "CREATE_PROMOTION_SUCCESS";
export const CREATE_PROMOTION_FAILURE = "CREATE_PROMOTION_FAILURE";

export const UPDATE_PROMOTION = "UPDATE_PROMOTION";
export const UPDATE_PROMOTION_PENDING = "UPDATE_PROMOTION_PENDING";
export const UPDATE_PROMOTION_SUCCESS = "UPDATE_PROMOTION_SUCCESS";
export const UPDATE_PROMOTION_FAILURE = "UPDATE_PROMOTION_FAILURE";

export const DELETE_PROMOTION = "DELETE_PROMOTION";
export const DELETE_PROMOTION_PENDING = "DELETE_PROMOTION_PENDING";
export const DELETE_PROMOTION_SUCCESS = "DELETE_PROMOTION_SUCCESS";
export const DELETE_PROMOTION_FAILURE = "DELETE_PROMOTION_FAILURE";

//=========get single promotion
export const READ_PROMOTION_BOOK_TICKET = "READ_PROMOTION_BOOK_TICKET";
export const READ_PROMOTION_BOOK_TICKET_PENDING = "READ_PROMOTION_BOOK_TICKET_PENDING";
export const READ_PROMOTION_BOOK_TICKET_SUCCESS = "READ_PROMOTION_BOOK_TICKET_SUCCESS";
export const READ_PROMOTION_BOOK_TICKET_FAILURE = "READ_PROMOTION_BOOK_TICKET_FAILURE";

export const CREATE_PROMOTION_BOOK_TICKET = "CREATE_PROMOTION_BOOK_TICKET";
export const CREATE_PROMOTION_BOOK_TICKET_PENDING = "CREATE_PROMOTION_BOOK_TICKET_PENDING";
export const CREATE_PROMOTION_BOOK_TICKET_SUCCESS = "CREATE_PROMOTION_BOOK_TICKET_SUCCESS";
export const CREATE_PROMOTION_BOOK_TICKET_FAILURE = "CREATE_PROMOTION_BOOK_TICKET_FAILURE";

export const UPDATE_PROMOTION_BOOK_TICKET = "UPDATE_PROMOTION_BOOK_TICKET";
export const UPDATE_PROMOTION_BOOK_TICKET_PENDING = "UPDATE_PROMOTION_BOOK_TICKET_PENDING";
export const UPDATE_PROMOTION_BOOK_TICKET_SUCCESS = "UPDATE_PROMOTION_BOOK_TICKET_SUCCESS";
export const UPDATE_PROMOTION_BOOK_TICKET_FAILURE = "UPDATE_PROMOTION_BOOK_TICKET_FAILURE";

export const DELETE_PROMOTION_BOOK_TICKET = "DELETE_PROMOTION_BOOK_TICKET";
export const DELETE_PROMOTION_BOOK_TICKET_PENDING = "DELETE_PROMOTION_BOOK_TICKET_PENDING";
export const DELETE_PROMOTION_BOOK_TICKET_SUCCESS = "DELETE_PROMOTION_BOOK_TICKET_SUCCESS";
export const DELETE_PROMOTION_BOOK_TICKET_FAILURE = "DELETE_PROMOTION_BOOK_TICKET_FAILURE";
//--PROMOTION

// TYPE PAYMENT
export const READ_TYPEPAYMENT = "READ_TYPEPAYMENT";
export const READ_TYPEPAYMENT_PENDING = "READ_TYPEPAYMENT_PENDING";
export const READ_TYPEPAYMENT_SUCCESS = "READ_TYPEPAYMENT_SUCCESS";
export const READ_TYPEPAYMENT_FAILURE = "READ_TYPEPAYMENT_FAILURE";
// -- TYPE PAYMENT

//BILL
export const READ_BILL = "READ_BILL";
export const READ_BILL_PENDING = "READ_BILL_PENDING";
export const READ_BILL_SUCCESS = "READ_BILL_SUCCESS";
export const READ_BILL_FAILURE = "READ_BILL_FAILURE";

export const CREATE_BILL = "CREATE_BILL";
export const CREATE_BILL_PENDING = "CREATE_BILL_PENDING";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAILURE = "CREATE_BILL_FAILURE";
//--BILL
//user
export const READ_USER = "READ_USER";
export const READ_USER_PENDING = "READ_USER_PENDING";
export const READ_USER_SUCCESS = "READ_USER_SUCCESS";
export const READ_USER_FAILURE = "READ_USER_FAILURE";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_PENDING = "CREATE_USER_PENDING";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
//end user
